### ISSUE TITLE
an error in the "create release" step

### ISSUE THREAD

**Issue by liuhq** [ellisonoswalt/aseprite_builder#9]
### first

![image](https://user-images.githubusercontent.com/48037182/225572207-41a61572-2079-4a13-9979-d7ea219b2101.png)

### then

![image](https://user-images.githubusercontent.com/48037182/225571232-88ad5e6e-b04c-4749-9c8e-4bd3fadfae64.png)

**Comment by liuhq** [comment]
sovled. go to _Settings>Actions>General>Workflow permissions_ and choose _Read and write permissions_

**Comment by ShayBox** [comment]
Read and write permissions doesn't seem to fix this anymore.
